import { useState, useEffect } from 'react';
import { useSelector } from 'react-redux';
import { Link, useNavigate } from 'react-router-dom';
import { orderAPI } from '../api/axiosInstance';
import PlanBadge from '../components/PlanBadge';
import toast from 'react-hot-toast';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { 
  FiPackage, FiSettings, FiShoppingBag, FiDownload, FiEye, 
  FiCheck, FiClock, FiX, FiArrowLeft, FiTrendingUp, FiDollarSign
} from 'react-icons/fi';

const STATUS_CONFIG = {
  pending: { label: 'Pending', color: 'bg-yellow-100 text-yellow-700', icon: FiClock },
  confirmed: { label: 'Confirmed', color: 'bg-blue-100 text-blue-700', icon: FiCheck },
  delivered: { label: 'Delivered', color: 'bg-green-100 text-green-700', icon: FiCheck },
  cancelled: { label: 'Cancelled', color: 'bg-red-100 text-red-700', icon: FiX }
};

const generateInvoicePDF = (order, vendor) => {
  const doc = new jsPDF();
  
  doc.setFillColor(37, 200, 102);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 20, 25);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`${vendor.businessName}`, 20, 33);
  
  doc.setTextColor(26, 26, 46);
  doc.setFontSize(10);
  let y = 55;
  
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 20, y);
  doc.setFont('helvetica', 'normal');
  y += 6;
  doc.text(order.customerName || 'Customer', 20, y);
  if (order.customerPhone) {
    y += 5;
    doc.text(order.customerPhone, 20, y);
  }
  
  doc.setFont('helvetica', 'bold');
  doc.text('Order Details:', 130, 55);
  doc.setFont('helvetica', 'normal');
  doc.text(`Order ID: ${order._id.slice(-8).toUpperCase()}`, 130, 63);
  doc.text(`Date: ${new Date(order.createdAt).toLocaleDateString()}`, 130, 70);
  doc.text(`Status: ${STATUS_CONFIG[order.status]?.label || order.status}`, 130, 77);
  
  y = 95;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Items:', 20, y);
  
  doc.autoTable({
    startY: y + 5,
    head: [['Item', 'Qty', 'Price', 'Total']],
    body: order.items.map(item => [
      item.name,
      item.qty,
      `₦${item.price.toLocaleString()}`,
      `₦${(item.price * item.qty).toLocaleString()}`
    ]),
    theme: 'striped',
    headStyles: { 
      fillColor: [26, 26, 46],
      textColor: 255,
      fontStyle: 'bold'
    },
    columnStyles: {
      2: { halign: 'right' },
      3: { halign: 'right' }
    },
    margin: { left: 20, right: 20 }
  });
  
  const finalY = doc.lastAutoTable.finalY + 10;
  
  doc.setFillColor(37, 200, 102);
  doc.rect(120, finalY, 70, 12, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`TOTAL: ₦${order.totalAmount.toLocaleString()}`, 125, finalY + 8);
  
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Thank you for your business!', 105, 280, { align: 'center' });
  doc.text('Generated by VendPadi', 105, 285, { align: 'center' });
  
  doc.save(`invoice-${order._id.slice(-8).toUpperCase()}.pdf`);
};

const generateReceiptPDF = (order, vendor) => {
  const doc = new jsPDF();
  
  doc.setFillColor(245, 166, 35);
  doc.rect(0, 0, 210, 30, 'F');
  
  doc.setTextColor(26, 26, 46);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('RECEIPT', 20, 20);
  
  doc.setTextColor(26, 26, 46);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(vendor.businessName, 20, 45);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Date: ${new Date(order.createdAt).toLocaleString()}`, 20, 53);
  doc.text(`Receipt #: ${order._id.slice(-8).toUpperCase()}`, 20, 60);
  
  let y = 75;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Items Purchased', 20, y);
  
  doc.autoTable({
    startY: y + 5,
    head: [['#', 'Item', 'Qty', 'Amount']],
    body: order.items.map((item, idx) => [
      idx + 1,
      item.name,
      item.qty,
      `₦${(item.price * item.qty).toLocaleString()}`
    ]),
    theme: 'grid',
    headStyles: { 
      fillColor: [245, 166, 35],
      textColor: 26,
      fontStyle: 'bold'
    },
    columnStyles: {
      3: { halign: 'right' }
    },
    margin: { left: 20, right: 20 }
  });
  
  const finalY = doc.lastAutoTable.finalY + 15;
  
  doc.setDrawColor(200, 200, 200);
  doc.line(120, finalY - 5, 190, finalY - 5);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('TOTAL PAID', 120, finalY + 5);
  doc.setTextColor(37, 200, 102);
  doc.text(`₦${order.totalAmount.toLocaleString()}`, 190, finalY + 5, { align: 'right' });
  
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Payment via WhatsApp Order', 105, 270, { align: 'center' });
  doc.text('Generated by VendPadi', 105, 275, { align: 'center' });
  
  doc.save(`receipt-${order._id.slice(-8).toUpperCase()}.pdf`);
};

const Orders = () => {
  const { vendor } = useSelector((state) => state.auth);
  const navigate = useNavigate();
  const [orders, setOrders] = useState([]);
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [selectedOrder, setSelectedOrder] = useState(null);

  const isPremium = vendor?.plan?.type === 'premium';

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      const [ordersRes, statsRes] = await Promise.all([
        orderAPI.getAll(),
        orderAPI.getStats()
      ]);
      setOrders(ordersRes.data);
      setStats(statsRes.data);
    } catch (error) {
      toast.error('Failed to load orders');
    } finally {
      setLoading(false);
    }
  };

  const handleStatusUpdate = async (orderId, status) => {
    try {
      await orderAPI.updateStatus(orderId, status);
      toast.success('Status updated');
      fetchData();
    } catch (error) {
      toast.error('Failed to update status');
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="w-12 h-12 border-4 border-padi-green border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Sidebar */}
      <div className="hidden lg:block fixed left-0 top-0 w-64 h-full bg-navy text-white p-6">
        <Link to="/" className="flex items-center gap-3 mb-8">
          <div className="w-10 h-10 bg-padi-green rounded-xl flex items-center justify-center">
            <span className="font-sora font-bold text-xl">V</span>
          </div>
          <span className="font-sora font-bold text-lg">VendPadi</span>
        </Link>

        <div className="mb-6">
          <div className="w-16 h-16 bg-padi-green/20 rounded-xl mx-auto flex items-center justify-center mb-3 overflow-hidden">
            {vendor?.logo ? (
              <img src={vendor.logo} alt="" className="w-full h-full object-cover" />
            ) : (
              <span className="text-3xl">🏪</span>
            )}
          </div>
          <h3 className="font-sora font-semibold text-center">{vendor?.businessName}</h3>
          <div className="flex justify-center mt-2">
            <PlanBadge plan={vendor?.plan} size="sm" />
          </div>
        </div>

        <nav className="space-y-2">
          <Link to="/dashboard" className="flex items-center gap-3 px-4 py-2.5 rounded-lg hover:bg-white/10 transition-colors">
            <FiPackage /> Products
          </Link>
          <Link to="/orders" className="flex items-center gap-3 px-4 py-2.5 rounded-lg bg-padi-green/20 text-padi-green">
            <FiShoppingBag /> Orders
          </Link>
          <Link to="/settings" className="flex items-center gap-3 px-4 py-2.5 rounded-lg hover:bg-white/10 transition-colors">
            ⚙️ Settings
          </Link>
        </nav>
      </div>

      {/* Main Content */}
      <div className="lg:ml-64">
        {/* Header */}
        <header className="bg-white border-b border-gray-100 px-6 py-4 sticky top-0 z-10">
          <div className="flex items-center gap-4">
            <button onClick={() => navigate(-1)} className="p-2 hover:bg-gray-100 rounded-lg lg:hidden">
              <FiArrowLeft />
            </button>
            <div>
              <h1 className="font-sora font-bold text-xl text-navy">Orders</h1>
              <p className="text-sm text-gray-500">{orders.length} total orders</p>
            </div>
          </div>
        </header>

        <div className="p-6">
          {/* Stats */}
          {stats && (
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
              <div className="bg-white p-5 rounded-2xl border border-gray-100">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-padi-green/10 rounded-xl flex items-center justify-center">
                    <FiShoppingBag className="text-padi-green" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-navy">{stats.totalOrders}</p>
                    <p className="text-xs text-gray-500">Total Orders</p>
                  </div>
                </div>
              </div>
              <div className="bg-white p-5 rounded-2xl border border-gray-100">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-yellow-100 rounded-xl flex items-center justify-center">
                    <FiClock className="text-yellow-600" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-navy">{stats.pendingOrders}</p>
                    <p className="text-xs text-gray-500">Pending</p>
                  </div>
                </div>
              </div>
              <div className="bg-white p-5 rounded-2xl border border-gray-100">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-green-100 rounded-xl flex items-center justify-center">
                    <FiCheck className="text-green-600" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-navy">{stats.deliveredOrders}</p>
                    <p className="text-xs text-gray-500">Delivered</p>
                  </div>
                </div>
              </div>
              <div className="bg-white p-5 rounded-2xl border border-gray-100">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-gold/10 rounded-xl flex items-center justify-center">
                    <FiDollarSign className="text-gold" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-navy">₦{stats.totalRevenue.toLocaleString()}</p>
                    <p className="text-xs text-gray-500">Revenue</p>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Premium Banner */}
          {!isPremium && (
            <div className="bg-gradient-to-r from-navy to-navy-light text-white p-5 rounded-2xl mb-6 flex items-center justify-between">
              <div className="flex items-center gap-4">
                <span className="text-3xl">👑</span>
                <div>
                  <h3 className="font-semibold">Upgrade to Premium</h3>
                  <p className="text-sm text-gray-300">Generate PDF invoices & receipts for your orders</p>
                </div>
              </div>
              <Link to="/settings" className="bg-gold hover:bg-gold/90 text-white px-5 py-2 rounded-xl font-medium transition-colors">
                Upgrade Now
              </Link>
            </div>
          )}

          {/* Orders List */}
          {orders.length === 0 ? (
            <div className="text-center py-16 bg-white rounded-2xl border border-gray-100">
              <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <FiShoppingBag className="text-4xl text-gray-300" />
              </div>
              <h3 className="font-sora font-semibold text-xl mb-2">No Orders Yet</h3>
              <p className="text-gray-500">Orders will appear here when customers place them.</p>
            </div>
          ) : (
            <div className="space-y-4">
              {orders.map((order) => {
                const StatusIcon = STATUS_CONFIG[order.status]?.icon || FiClock;
                return (
                  <div key={order._id} className="bg-white rounded-2xl border border-gray-100 p-5 hover:shadow-md transition-shadow">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <span className="font-semibold text-navy">#{order._id.slice(-8).toUpperCase()}</span>
                          <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium ${STATUS_CONFIG[order.status]?.color}`}>
                            <StatusIcon size={12} />
                            {STATUS_CONFIG[order.status]?.label}
                          </span>
                        </div>
                        <p className="text-sm text-gray-500">
                          {order.customerName} • {order.items.length} item{order.items.length !== 1 ? 's' : ''}
                        </p>
                        <p className="text-xs text-gray-400 mt-1">
                          {new Date(order.createdAt).toLocaleString()}
                        </p>
                      </div>
                      
                      <div className="flex items-center gap-4">
                        <span className="font-bold text-xl text-padi-green">₦{order.totalAmount.toLocaleString()}</span>
                        
                        <div className="flex items-center gap-2">
                          <button
                            onClick={() => setSelectedOrder(order)}
                            className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
                            title="View Details"
                          >
                            <FiEye className="text-gray-500" />
                          </button>
                          
                          {isPremium && (
                            <>
                              <button
                                onClick={() => generateInvoicePDF(order, vendor)}
                                className="p-2 hover:bg-padi-green/10 rounded-lg transition-colors"
                                title="Download Invoice"
                              >
                                <FiDownload className="text-padi-green" />
                              </button>
                            </>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* Order Detail Modal */}
      {selectedOrder && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={() => setSelectedOrder(null)}>
          <div className="bg-white rounded-2xl max-w-lg w-full max-h-[90vh] overflow-y-auto" onClick={e => e.stopPropagation()}>
            <div className="p-5 border-b flex items-center justify-between sticky top-0 bg-white">
              <div>
                <h2 className="font-sora font-bold text-lg">Order Details</h2>
                <p className="text-sm text-gray-500">#{selectedOrder._id.slice(-8).toUpperCase()}</p>
              </div>
              <button onClick={() => setSelectedOrder(null)} className="p-2 hover:bg-gray-100 rounded-lg">
                <FiX />
              </button>
            </div>
            
            <div className="p-5">
              {(() => {
                const StatusIcon = STATUS_CONFIG[selectedOrder.status]?.icon || FiClock;
                return (
                  <div className="flex items-center justify-between mb-4">
                    <span className={`inline-flex items-center gap-1 px-3 py-1.5 rounded-full text-sm font-medium ${STATUS_CONFIG[selectedOrder.status]?.color}`}>
                      <StatusIcon size={14} />
                      {STATUS_CONFIG[selectedOrder.status]?.label}
                    </span>
                    <span className="font-bold text-2xl text-padi-green">₦{selectedOrder.totalAmount.toLocaleString()}</span>
                  </div>
                );
              })()}
              
              <div className="grid grid-cols-2 gap-4 mb-6">
                <div>
                  <p className="text-xs text-gray-500">Customer</p>
                  <p className="font-medium">{selectedOrder.customerName || 'Anonymous'}</p>
                </div>
                <div>
                  <p className="text-xs text-gray-500">Phone</p>
                  <p className="font-medium">{selectedOrder.customerPhone || 'N/A'}</p>
                </div>
                <div>
                  <p className="text-xs text-gray-500">Date</p>
                  <p className="font-medium">{new Date(selectedOrder.createdAt).toLocaleString()}</p>
                </div>
                <div>
                  <p className="text-xs text-gray-500">Items</p>
                  <p className="font-medium">{selectedOrder.items.length} item{selectedOrder.items.length !== 1 ? 's' : ''}</p>
                </div>
              </div>
              
              <h3 className="font-semibold mb-3">Items</h3>
              <div className="space-y-3 mb-6">
                {selectedOrder.items.map((item, idx) => (
                  <div key={idx} className="flex items-center justify-between bg-gray-50 p-3 rounded-xl">
                    <div>
                      <p className="font-medium">{item.name}</p>
                      <p className="text-sm text-gray-500">{item.qty} × ₦{item.price.toLocaleString()}</p>
                    </div>
                    <span className="font-bold">₦{(item.price * item.qty).toLocaleString()}</span>
                  </div>
                ))}
              </div>
              
              {selectedOrder.note && (
                <div className="mb-6">
                  <h3 className="font-semibold mb-2">Note</h3>
                  <p className="text-gray-600 bg-yellow-50 p-3 rounded-xl">{selectedOrder.note}</p>
                </div>
              )}
              
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-2">Update Status</label>
                <div className="flex flex-wrap gap-2">
                  {Object.entries(STATUS_CONFIG).map(([status, config]) => (
                    <button
                      key={status}
                      onClick={() => handleStatusUpdate(selectedOrder._id, status)}
                      disabled={selectedOrder.status === status}
                      className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                        selectedOrder.status === status
                          ? `${config.color} cursor-not-allowed`
                          : 'bg-gray-100 hover:bg-gray-200'
                      }`}
                    >
                      {config.label}
                    </button>
                  ))}
                </div>
              </div>
              
              {isPremium && (
                <div className="flex gap-3">
                  <button
                    onClick={() => { generateInvoicePDF(selectedOrder, vendor); setSelectedOrder(null); }}
                    className="flex-1 btn-primary flex items-center justify-center gap-2"
                  >
                    <FiDownload /> Invoice PDF
                  </button>
                  <button
                    onClick={() => { generateReceiptPDF(selectedOrder, vendor); setSelectedOrder(null); }}
                    className="flex-1 bg-gold hover:bg-gold/90 text-white py-3 rounded-xl font-semibold flex items-center justify-center gap-2"
                  >
                    <FiDownload /> Receipt PDF
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Orders;
