import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const loadImageAsBase64 = (url) => {
  return new Promise((resolve) => {
    if (!url) {
      resolve(null);
      return;
    }
    const img = new Image();
    img.crossOrigin = "Anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      ctx.drawImage(img, 0, 0);
      const dataUrl = canvas.toDataURL("image/png");
      resolve(dataUrl);
    };
    img.onerror = () => resolve(null);
    img.src = url;
  });
};

const formatOrderDate = (date) => {
  return new Date(date).toLocaleDateString("en-NG", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
};

const getCustomerDisplay = (order) => {
  return order.customerName || order.customerPhone || "Walk-in Customer";
};

export const generateInvoicePDF = async (order, vendor) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const logoData = await loadImageAsBase64(vendor?.logo);

  doc.setFillColor(37, 200, 102);
  doc.rect(0, 0, pageWidth, 40, "F");

  if (logoData) {
    doc.addImage(logoData, "PNG", 15, 8, 20, 20);
  }

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", logoData ? 42 : 15, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  if (logoData) {
    doc.text(vendor?.businessName || "Store", 42, 28);
    if (vendor?.phone) {
      doc.text(`Tel: ${vendor.phone}`, 42, 35);
    }
  } else {
    doc.text(vendor?.businessName || "Store", 15, 28);
    if (vendor?.phone) {
      doc.text(`Tel: ${vendor.phone}`, 15, 35);
    }
  }

  doc.setTextColor(26, 26, 46);
  let y = 55;

  const customerDisplay = getCustomerDisplay(order);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Bill To:", 20, y);
  doc.setFont("helvetica", "normal");
  y += 7;
  doc.setFontSize(10);
  doc.text(customerDisplay, 20, y);

  doc.setFont("helvetica", "bold");
  doc.text("Order Details:", 120, 60);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`Order ID: ${order.shortId || order._id.slice(-8).toUpperCase()}`, 120, 68);
  doc.text(`Date: ${formatOrderDate(order.createdAt)}`, 120, 75);
  doc.text(`Status: ${order.status?.charAt(0).toUpperCase() + order.status?.slice(1) || order.status}`, 120, 82);

  y = 100;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Items:", 20, y);

  autoTable(doc, {
    startY: y + 5,
    head: [["#", "Item Description", "Qty", "Unit Price", "Total"]],
    body: order.items.map((item, idx) => [
      idx + 1,
      item.name,
      item.qty,
      "NGN " + item.price.toLocaleString(),
      "NGN " + (item.price * item.qty).toLocaleString(),
    ]),
    theme: "striped",
    headStyles: {
      fillColor: [26, 26, 46],
      textColor: 255,
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 12 },
      1: { cellWidth: 80 },
      2: { cellWidth: 20, halign: "center" },
      3: { cellWidth: 35, halign: "right" },
      4: { cellWidth: 35, halign: "right" },
    },
    margin: { left: 20, right: 20 },
  });

  const finalY = (doc.lastAutoTable?.finalY ?? y + 40) + 12;

  doc.setFillColor(37, 200, 102);
  doc.rect(110, finalY, 80, 14, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`TOTAL: NGN ${order.totalAmount.toLocaleString()}`, 115, finalY + 9);

  if (order.deliveryInfo?.zone) {
    doc.setTextColor(80, 80, 80);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(`Delivery (${order.deliveryInfo.zone}): NGN ${order.deliveryInfo.fee.toLocaleString()}`, 20, finalY + 22);
  }

  if (order.note) {
    doc.setTextColor(80, 80, 80);
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.text(`Note: ${order.note}`, 20, finalY + 25);
  }

  doc.setTextColor(120, 120, 120);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Thank you for your business!", pageWidth / 2, 275, {
    align: "center",
  });
  doc.text("Generated by VendPadi | vendpadi.com", pageWidth / 2, 280, {
    align: "center",
  });

  doc.save(`Invoice-${order.shortId || order._id.slice(-8).toUpperCase()}.pdf`);
};

export const generateReceiptPDF = async (order, vendor) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const logoData = await loadImageAsBase64(vendor?.logo);

  doc.setFillColor(245, 166, 35);
  doc.rect(0, 0, pageWidth, 35, "F");

  if (logoData) {
    doc.addImage(logoData, "PNG", 15, 8, 18, 18);
  }

  doc.setTextColor(26, 26, 46);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("RECEIPT", logoData ? 40 : 15, 22);

  if (logoData) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(vendor?.businessName || "Store", 40, 28);
    doc.setFont("helvetica", "normal");
    if (vendor?.phone) {
      doc.text(`Tel: ${vendor.phone}`, 40, 34);
    }
  } else {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(vendor?.businessName || "Store", 15, 26);
    doc.setFont("helvetica", "normal");
    if (vendor?.phone) {
      doc.text(`Tel: ${vendor.phone}`, 15, 33);
    }
  }

  doc.line(15, 45, pageWidth - 15, 45);

  let y = 55;
  const customerDisplay = getCustomerDisplay(order);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`Customer: ${customerDisplay}`, 15, y);
  y += 10;
  doc.text("Items Purchased", 15, y);

  autoTable(doc, {
    startY: y + 5,
    head: [["#", "Item", "Qty", "Amount"]],
    body: order.items.map((item, idx) => [
      idx + 1,
      item.name,
      item.qty,
      "NGN " + (item.price * item.qty).toLocaleString(),
    ]),
    theme: "grid",
    headStyles: {
      fillColor: [245, 166, 35],
      textColor: [26, 26, 46],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 12, halign: "center" },
      1: { cellWidth: 95 },
      2: { cellWidth: 20, halign: "center" },
      3: { cellWidth: 48, halign: "right" },
    },
    margin: { left: 15, right: 15 },
  });

  const finalY = (doc.lastAutoTable?.finalY ?? y + 40) + 12;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(100, finalY, pageWidth - 15, finalY);

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(26, 26, 46);
  doc.text("TOTAL PAID:", 100, finalY + 10);
  doc.setTextColor(37, 200, 102);
  doc.setFontSize(14);
  doc.text(
    "NGN " + order.totalAmount.toLocaleString(),
    pageWidth - 15,
    finalY + 10,
    { align: "right" },
  );

  if (order.deliveryInfo?.zone) {
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    doc.text(
      `Delivery (${order.deliveryInfo.zone}): NGN ${order.deliveryInfo.fee.toLocaleString()}`,
      pageWidth - 15,
      finalY + 18,
      { align: "right" },
    );
  }

  doc.setTextColor(100, 100, 100);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Payment via WhatsApp Order", pageWidth / 2, 265, {
    align: "center",
  });
  doc.text("Generated by VendPadi | vendpadi.com", pageWidth / 2, 270, {
    align: "center",
  });

  doc.save(`Receipt-${order.shortId || order._id.slice(-8).toUpperCase()}.pdf`);
};
